apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-api
  template:
    metadata:
      labels:
        app: my-app-api
    spec:
      serviceAccountName: shinmin-service-account
      containers:
      - name: my-app-api
        image: gcr.io/${GCP_PROJECT_ID}/my-app-api:${GITHUB_SHA}  # This will be updated by GitHub Actions
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: my-app-api
