apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-api
  template:
    metadata:
      labels:
        app: my-app-api
    spec:
      serviceAccountName: Shinmin-Service-Account
      containers:
      - name: my-app-api
        image: gcr.io/${GCP_PROJECT_ID}/my-app-api:${GITHUB_SHA}  # This will be updated by GitHub Actions
        ports:
        - containerPort: 3000

      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
        args:
          - "--structured-logs"
          - "--port=5432"
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: my-app-api
